[package]
name = "farmsim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.1"
serde = "1.0.130"
serde_json = "1.0.72"
serde_derive = "1.0.130"
